name: Build macOS App

on:
  push:
    branches: [main, master]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build macOS .app
      run: |
        pyinstaller main.spec

    - name: Upload .app bundle
      uses: actions/upload-artifact@v3
      with:
        name: ControlSerialMacApp
        path: dist/ControlSerialMacApp.app